name: Package
on:
  workflow_call:
    inputs:
      version:
        description: SourceGit package version
        required: true
        type: string
jobs:
  windows:
    name: Package Windows x64
    runs-on: windows-2022
    steps:
      - name: Checkout sources
        uses: actions/checkout@v6
      - name: Download build
        uses: actions/download-artifact@v8
        with:
          name: sourcegit.win-x64
          path: build/SourceGit
      - name: Package
        shell: pwsh
        env:
          VERSION: ${{ inputs.version }}
          RUNTIME: win-x64
        run: ./build/scripts/package.win.ps1
      - name: Upload package artifact
        uses: actions/upload-artifact@v7
        with:
          name: package.win-x64
          path: build/sourcegit_*.zip
      - name: Delete temp artifacts
        uses: geekyeggo/delete-artifact@v6
        with:
          name: sourcegit.win-x64
  linux:
    name: Package Linux x64
    runs-on: ubuntu-latest
    container: ubuntu:20.04
    steps:
      - name: Checkout sources
        uses: actions/checkout@v6
      - name: Download package dependencies
        run: |
          export DEBIAN_FRONTEND=noninteractive
          ln -fs /usr/share/zoneinfo/Etc/UTC /etc/localtime
          apt-get update
          apt-get install -y curl wget git dpkg-dev fakeroot tzdata zip unzip desktop-file-utils rpm libfuse2 file build-essential binutils
      - name: Download build
        uses: actions/download-artifact@v8
        with:
          name: sourcegit.linux-x64
          path: build
      - name: Package
        env:
          VERSION: ${{ inputs.version }}
          RUNTIME: linux-x64
          APPIMAGE_EXTRACT_AND_RUN: 1
        run: |
          mkdir build/SourceGit
          tar -xf build/sourcegit.linux-x64.tar -C build/SourceGit
          ./build/scripts/package.linux.sh
      - name: Upload package artifacts
        uses: actions/upload-artifact@v7
        with:
          name: package.linux-x64
          path: |
            build/sourcegit-*.AppImage
            build/sourcegit_*.deb
            build/sourcegit-*.rpm
      - name: Delete temp artifacts
        uses: geekyeggo/delete-artifact@v6
        with:
          name: sourcegit.linux-x64
